name: ManualBuildOnly
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-quality: 'ga'
    - name: Restore dependencies
      run: dotnet restore ./src/MinVer.Example/MinVer.Example.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release ./src/MinVer.Example/MinVer.Example.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/MinVer.Example/MinVer.Example.csproj
