name: OnPush develop
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-quality: 'ga'
    - name: Restore dependencies
      run: dotnet restore ./src/MinVer.Example/MinVer.Example.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release ./src/MinVer.Example/MinVer.Example.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/MinVer.Example/MinVer.Example.csproj
    - name: publish on nuget.org
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/MinVer.Example/MinVer.Example.csproj
        PACKAGE_NAME: MinVer.Example
        VERSION_STATIC: 1.0.0          
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: false
